# ABOUT: git-hub workflow to automatically check code sanity on commits to main branch.

name: Commit Sanity

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Standard python with external dependencies cached from project
    # requirements to speedup build times.
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: "pip"
        cache-dependency-path: requirements/requirements*.txt

    # Fake point a virtual environment to git-hubs cached package location
    # so that CI workflows can work with our helper scripts.
    - name: Setup Environment
      run: |
        echo VIRTUAL_ENV=${Python_ROOT_DIR} >> ${GITHUB_ENV};

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip;
        pip install flake8 pytest;
        ./run --install;

    # Stop build if there are syntax errors or undefined symbols but treat all
    # other issues as warnings.
    - name: Lint Code Correctness
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics;
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics;

    # Invoke & report on all tests as configured.
    - name: Test Suite
      run: |
        ./run --test;
        genbadge tests \
            --input-file runtime/code_tests/report.xml \
            --output-file runtime/code_tests/badge.svg;
        genbadge coverage \
            --input-file runtime/code_coverage/report.xml \
            --output-file runtime/code_coverage/badge.svg;

    # Publish badges via hidden gists. See 
    # https://github.com/marketplace/actions/deploy-to-gist
    - name: Coverage Badge
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_SECRET }}
        gist_id: eb12b64cf81f991888c6bfd3f3419064
        gist_file_name: coverage_badge.svg
        file_path: runtime/code_coverage/badge.svg
        file_type: binary

    - name: Test Badge
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_SECRET }}
        gist_id: eb12b64cf81f991888c6bfd3f3419064
        gist_file_name: tests_badge.svg
        file_path: runtime/code_tests/badge.svg
        file_type: binary

    # Archive run time artifact to troubleshoot within a few days.
    - name: Upload Runtime Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: runtime
        path: runtime
        retention-days: 3

