name: Build & Deploy Docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: requirements/requirements_document.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements/requirements_document.txt
  
      - name: Build MkDocs
        run: |
          mkdocs gh-deploy --force --clean --verbose
