# ABOUT: git-hub workflow to automatically check code sanity on commits to main branch.

name: Commit Sanity

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Setup Environment
      run: |
        echo VIRTUAL_ENV=${Python_ROOT_DIR} >> ${GITHUB_ENV};

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip;
        pip install flake8 pytest;
        #for req in requirements/requirements_*.txt; do  pip install -r "${req}"; done;
        ./run --install;

    # Stop build if there are syntax errors or undefined names but treat all
    # other errors as warnings.
    - name: Lint Code Correctness
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics;
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics;

    - name: Test Suite
      run: |
        ./run --test;
